### PR TITLE
Add more docs for SNS

### PR DESCRIPTION
**Pull request by frioux**

### CODE REVIEW

**Comment by michaelwittig** [comment]
Hi @frioux Thanks for your work. Can you provide the source of this information?

**Comment by frioux** [comment]
Sorry, I could have swore I included details in the initial PR.  Two things:

 * https://docs.aws.amazon.com/sns/latest/dg/AccessPolicyLanguage_UseCases_Sns.html has some documentation
 * I experimented with the policy generator, for what it's worth.

**Comment by frioux** [comment]
AWS also linked to this: https://docs.aws.amazon.com/sns/latest/dg/UsingIAMwithSNS.html, hiwch is not as clear as the other link I posted a couple minutes ago, but better than nothing

**Comment by michaelwittig** [comment]
@frioux sorry for my super late reply... there is a bigger merge conflict here. Something also looks strange because all lines are marked as changed. Maybe this is related to line endings? Which editor are you using? Maybe the issue is `\n` vs `\r\n` but I'm not sure...

**Comment by frioux** [comment]
I didn't change newlines (you can tell by looking at the commit itself at the top of the PR) but I did change almost every line.  I can update the PR so that the merge conflict goes away.  Will do later.

**Comment by michaelwittig** [comment]
closed because of inactivity. feel free to reopen.

**Pull request closed without merging**
